package com.suneee.mapper;

import com.suneee.entity.AlgorithmPath;
import com.suneee.entity.AlgorithmPathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlgorithmPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    long countByExample(AlgorithmPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int deleteByExample(AlgorithmPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int insert(AlgorithmPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int insertSelective(AlgorithmPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    List<AlgorithmPath> selectByExample(AlgorithmPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    AlgorithmPath selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") AlgorithmPath record, @Param("example") AlgorithmPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int updateByExample(@Param("record") AlgorithmPath record, @Param("example") AlgorithmPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int updateByPrimaryKeySelective(AlgorithmPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table algorithm_path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    int updateByPrimaryKey(AlgorithmPath record);
    
    AlgorithmPath selectByPath(String path);
}