package com.suneee.mapper;

import com.suneee.entity.AlgorithmInfo;
import com.suneee.entity.AlgorithmInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * 
 * @author zmd
 *
 */
public interface AlgorithmInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param example
	 * @return
	 */
	long countByExample(AlgorithmInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param example
	 * @return
	 */
	int deleteByExample(AlgorithmInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param id
	 * @return
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @return
	 */
	int insert(AlgorithmInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @return
	 */
	int insertSelective(AlgorithmInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param example
	 * @return
	 */
	List<AlgorithmInfo> selectByExample(AlgorithmInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param id
	 * @return
	 */
	AlgorithmInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @param example
	 * @return
	 */
	int updateByExampleSelective(@Param("record") AlgorithmInfo record, @Param("example") AlgorithmInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @param example
	 * @return
	 */
	int updateByExample(@Param("record") AlgorithmInfo record, @Param("example") AlgorithmInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @return
	 */
	int updateByPrimaryKeySelective(AlgorithmInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table algorithm_info
	 * @mbg.generated  Mon May 21 18:12:35 CST 2018
	 * @param record
	 * @return
	 */
	int updateByPrimaryKey(AlgorithmInfo record);
}