package com.suneee.mapper;

import com.suneee.entity.RuleLimit;
import com.suneee.entity.RuleLimitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    long countByExample(RuleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int deleteByExample(RuleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int insert(RuleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int insertSelective(RuleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    List<RuleLimit> selectByExample(RuleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    RuleLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") RuleLimit record, @Param("example") RuleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int updateByExample(@Param("record") RuleLimit record, @Param("example") RuleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int updateByPrimaryKeySelective(RuleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    int updateByPrimaryKey(RuleLimit record);
    
    RuleLimit selectByAlgorithm(Integer id);
}