package com.suneee.mapper;

import com.suneee.entity.SecretKeyInfo;
import com.suneee.entity.SecretKeyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecretKeyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    long countByExample(SecretKeyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int deleteByExample(SecretKeyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int insert(SecretKeyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int insertSelective(SecretKeyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    List<SecretKeyInfo> selectByExample(SecretKeyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    SecretKeyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") SecretKeyInfo record, @Param("example") SecretKeyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int updateByExample(@Param("record") SecretKeyInfo record, @Param("example") SecretKeyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int updateByPrimaryKeySelective(SecretKeyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secret_key_info
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    int updateByPrimaryKey(SecretKeyInfo record);
}