package com.suneee.mapper;

import com.suneee.entity.TaskInfo;
import com.suneee.entity.TaskInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * 
 * @author zmd
 *
 */
public interface TaskInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param example
	 * @return
	 */
	long countByExample(TaskInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param example
	 * @return
	 */
	int deleteByExample(TaskInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	  * @param id
	  * @return
	  */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @return
	 */
	int insert(TaskInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @return
	 */
	int insertSelective(TaskInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param example
	 * @return
	 */
	List<TaskInfo> selectByExample(TaskInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param id
	 * @return
	 */
	TaskInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @param example
	 * @return
	 */
	int updateByExampleSelective(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @param example
	 * @return
	 */
	int updateByExample(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @return
	 */
	int updateByPrimaryKeySelective(TaskInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_info
	 * @mbg.generated  Tue May 15 14:44:20 CST 2018
	 * @param record
	 * @return
	 */
	int updateByPrimaryKey(TaskInfo record);
}