package com.suneee.entity;

import java.util.Date;

public class AlgorithmCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algo_comp.relation_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Integer relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algo_comp.algorithm_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Integer algorithmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algo_comp.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private String compCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algo_comp.status
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algo_comp.createtime
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algo_comp.relation_id
     *
     * @return the value of algo_comp.relation_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algo_comp.relation_id
     *
     * @param relationId the value for algo_comp.relation_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algo_comp.algorithm_id
     *
     * @return the value of algo_comp.algorithm_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Integer getAlgorithmId() {
        return algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algo_comp.algorithm_id
     *
     * @param algorithmId the value for algo_comp.algorithm_id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setAlgorithmId(Integer algorithmId) {
        this.algorithmId = algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algo_comp.comp_code
     *
     * @return the value of algo_comp.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public String getCompCode() {
        return compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algo_comp.comp_code
     *
     * @param compCode the value for algo_comp.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setCompCode(String compCode) {
        this.compCode = compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algo_comp.status
     *
     * @return the value of algo_comp.status
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algo_comp.status
     *
     * @param status the value for algo_comp.status
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algo_comp.createtime
     *
     * @return the value of algo_comp.createtime
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algo_comp.createtime
     *
     * @param createtime the value for algo_comp.createtime
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}