package com.suneee.entity;

public class GatewayRoute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.path
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.service_id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private String serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.url
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.retryable
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private Boolean retryable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.enabled
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.strip_prefix
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private Integer stripPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_route.api_name
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    private String apiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.id
     *
     * @return the value of gateway_route.id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.id
     *
     * @param id the value for gateway_route.id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.path
     *
     * @return the value of gateway_route.path
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.path
     *
     * @param path the value for gateway_route.path
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.service_id
     *
     * @return the value of gateway_route.service_id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.service_id
     *
     * @param serviceId the value for gateway_route.service_id
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.url
     *
     * @return the value of gateway_route.url
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.url
     *
     * @param url the value for gateway_route.url
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.retryable
     *
     * @return the value of gateway_route.retryable
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public Boolean getRetryable() {
        return retryable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.retryable
     *
     * @param retryable the value for gateway_route.retryable
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setRetryable(Boolean retryable) {
        this.retryable = retryable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.enabled
     *
     * @return the value of gateway_route.enabled
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.enabled
     *
     * @param enabled the value for gateway_route.enabled
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.strip_prefix
     *
     * @return the value of gateway_route.strip_prefix
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public Integer getStripPrefix() {
        return stripPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.strip_prefix
     *
     * @param stripPrefix the value for gateway_route.strip_prefix
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setStripPrefix(Integer stripPrefix) {
        this.stripPrefix = stripPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_route.api_name
     *
     * @return the value of gateway_route.api_name
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_route.api_name
     *
     * @param apiName the value for gateway_route.api_name
     *
     * @mbg.generated Mon Jun 25 09:24:05 CST 2018
     */
    public void setApiName(String apiName) {
        this.apiName = apiName;
    }
}