package com.suneee.entity;

import java.util.Date;

/**
 * 
 * @author zmd
 *
 */
public class AlgorithmInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.id
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.name
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.img
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.path
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.type
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.creator
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.version
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.size
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.descption
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String descption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.status
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.create_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_info.update_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.id
     *
     * @return the value of algorithm_info.id
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.id
     *
     * @param id the value for algorithm_info.id
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.name
     *
     * @return the value of algorithm_info.name
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.name
     *
     * @param name the value for algorithm_info.name
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.img
     *
     * @return the value of algorithm_info.img
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.img
     *
     * @param img the value for algorithm_info.img
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.path
     *
     * @return the value of algorithm_info.path
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.path
     *
     * @param path the value for algorithm_info.path
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.type
     *
     * @return the value of algorithm_info.type
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.type
     *
     * @param type the value for algorithm_info.type
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.creator
     *
     * @return the value of algorithm_info.creator
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.creator
     *
     * @param creator the value for algorithm_info.creator
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.version
     *
     * @return the value of algorithm_info.version
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.version
     *
     * @param version the value for algorithm_info.version
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.size
     *
     * @return the value of algorithm_info.size
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.size
     *
     * @param size the value for algorithm_info.size
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.descption
     *
     * @return the value of algorithm_info.descption
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getDescption() {
        return descption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.descption
     *
     * @param descption the value for algorithm_info.descption
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setDescption(String descption) {
        this.descption = descption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.status
     *
     * @return the value of algorithm_info.status
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.status
     *
     * @param status the value for algorithm_info.status
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.create_time
     *
     * @return the value of algorithm_info.create_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.create_time
     *
     * @param createTime the value for algorithm_info.create_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_info.update_time
     *
     * @return the value of algorithm_info.update_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_info.update_time
     *
     * @param updateTime the value for algorithm_info.update_time
     *
     * @mbg.generated Mon Jun 11 10:50:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}