package com.suneee.entity;

import java.util.Date;

public class AlgorithmPath {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_path.id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_path.path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_path.algorithm_id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    private Integer algorithmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithm_path.create_time
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_path.id
     *
     * @return the value of algorithm_path.id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_path.id
     *
     * @param id the value for algorithm_path.id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_path.path
     *
     * @return the value of algorithm_path.path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_path.path
     *
     * @param path the value for algorithm_path.path
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_path.algorithm_id
     *
     * @return the value of algorithm_path.algorithm_id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public Integer getAlgorithmId() {
        return algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_path.algorithm_id
     *
     * @param algorithmId the value for algorithm_path.algorithm_id
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public void setAlgorithmId(Integer algorithmId) {
        this.algorithmId = algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithm_path.create_time
     *
     * @return the value of algorithm_path.create_time
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithm_path.create_time
     *
     * @param createTime the value for algorithm_path.create_time
     *
     * @mbg.generated Mon Jun 25 15:44:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}