package com.suneee.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.suneee.utils.Pager;

public class RuleLimitExample extends Pager{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public RuleLimitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddNumIsNull() {
            addCriterion("add_num is null");
            return (Criteria) this;
        }

        public Criteria andAddNumIsNotNull() {
            addCriterion("add_num is not null");
            return (Criteria) this;
        }

        public Criteria andAddNumEqualTo(Integer value) {
            addCriterion("add_num =", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumNotEqualTo(Integer value) {
            addCriterion("add_num <>", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumGreaterThan(Integer value) {
            addCriterion("add_num >", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_num >=", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumLessThan(Integer value) {
            addCriterion("add_num <", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumLessThanOrEqualTo(Integer value) {
            addCriterion("add_num <=", value, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumIn(List<Integer> values) {
            addCriterion("add_num in", values, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumNotIn(List<Integer> values) {
            addCriterion("add_num not in", values, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumBetween(Integer value1, Integer value2) {
            addCriterion("add_num between", value1, value2, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddNumNotBetween(Integer value1, Integer value2) {
            addCriterion("add_num not between", value1, value2, "addNum");
            return (Criteria) this;
        }

        public Criteria andAddDayIsNull() {
            addCriterion("add_day is null");
            return (Criteria) this;
        }

        public Criteria andAddDayIsNotNull() {
            addCriterion("add_day is not null");
            return (Criteria) this;
        }

        public Criteria andAddDayEqualTo(Integer value) {
            addCriterion("add_day =", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayNotEqualTo(Integer value) {
            addCriterion("add_day <>", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayGreaterThan(Integer value) {
            addCriterion("add_day >", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_day >=", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayLessThan(Integer value) {
            addCriterion("add_day <", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayLessThanOrEqualTo(Integer value) {
            addCriterion("add_day <=", value, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayIn(List<Integer> values) {
            addCriterion("add_day in", values, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayNotIn(List<Integer> values) {
            addCriterion("add_day not in", values, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayBetween(Integer value1, Integer value2) {
            addCriterion("add_day between", value1, value2, "addDay");
            return (Criteria) this;
        }

        public Criteria andAddDayNotBetween(Integer value1, Integer value2) {
            addCriterion("add_day not between", value1, value2, "addDay");
            return (Criteria) this;
        }

        public Criteria andSurplusNumIsNull() {
            addCriterion("surplus_num is null");
            return (Criteria) this;
        }

        public Criteria andSurplusNumIsNotNull() {
            addCriterion("surplus_num is not null");
            return (Criteria) this;
        }

        public Criteria andSurplusNumEqualTo(Integer value) {
            addCriterion("surplus_num =", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumNotEqualTo(Integer value) {
            addCriterion("surplus_num <>", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumGreaterThan(Integer value) {
            addCriterion("surplus_num >", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("surplus_num >=", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumLessThan(Integer value) {
            addCriterion("surplus_num <", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumLessThanOrEqualTo(Integer value) {
            addCriterion("surplus_num <=", value, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumIn(List<Integer> values) {
            addCriterion("surplus_num in", values, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumNotIn(List<Integer> values) {
            addCriterion("surplus_num not in", values, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumBetween(Integer value1, Integer value2) {
            addCriterion("surplus_num between", value1, value2, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSurplusNumNotBetween(Integer value1, Integer value2) {
            addCriterion("surplus_num not between", value1, value2, "surplusNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumIsNull() {
            addCriterion("sdk_num is null");
            return (Criteria) this;
        }

        public Criteria andSdkNumIsNotNull() {
            addCriterion("sdk_num is not null");
            return (Criteria) this;
        }

        public Criteria andSdkNumEqualTo(Integer value) {
            addCriterion("sdk_num =", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumNotEqualTo(Integer value) {
            addCriterion("sdk_num <>", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumGreaterThan(Integer value) {
            addCriterion("sdk_num >", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sdk_num >=", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumLessThan(Integer value) {
            addCriterion("sdk_num <", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumLessThanOrEqualTo(Integer value) {
            addCriterion("sdk_num <=", value, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumIn(List<Integer> values) {
            addCriterion("sdk_num in", values, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumNotIn(List<Integer> values) {
            addCriterion("sdk_num not in", values, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumBetween(Integer value1, Integer value2) {
            addCriterion("sdk_num between", value1, value2, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andSdkNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sdk_num not between", value1, value2, "sdkNum");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCompCodeIsNull() {
            addCriterion("comp_code is null");
            return (Criteria) this;
        }

        public Criteria andCompCodeIsNotNull() {
            addCriterion("comp_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompCodeEqualTo(String value) {
            addCriterion("comp_code =", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotEqualTo(String value) {
            addCriterion("comp_code <>", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeGreaterThan(String value) {
            addCriterion("comp_code >", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeGreaterThanOrEqualTo(String value) {
            addCriterion("comp_code >=", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeLessThan(String value) {
            addCriterion("comp_code <", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeLessThanOrEqualTo(String value) {
            addCriterion("comp_code <=", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeLike(String value) {
            addCriterion("comp_code like", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotLike(String value) {
            addCriterion("comp_code not like", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeIn(List<String> values) {
            addCriterion("comp_code in", values, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotIn(List<String> values) {
            addCriterion("comp_code not in", values, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeBetween(String value1, String value2) {
            addCriterion("comp_code between", value1, value2, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotBetween(String value1, String value2) {
            addCriterion("comp_code not between", value1, value2, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompNameIsNull() {
            addCriterion("comp_name is null");
            return (Criteria) this;
        }

        public Criteria andCompNameIsNotNull() {
            addCriterion("comp_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompNameEqualTo(String value) {
            addCriterion("comp_name =", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotEqualTo(String value) {
            addCriterion("comp_name <>", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameGreaterThan(String value) {
            addCriterion("comp_name >", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameGreaterThanOrEqualTo(String value) {
            addCriterion("comp_name >=", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLessThan(String value) {
            addCriterion("comp_name <", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLessThanOrEqualTo(String value) {
            addCriterion("comp_name <=", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLike(String value) {
            addCriterion("comp_name like", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotLike(String value) {
            addCriterion("comp_name not like", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameIn(List<String> values) {
            addCriterion("comp_name in", values, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotIn(List<String> values) {
            addCriterion("comp_name not in", values, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameBetween(String value1, String value2) {
            addCriterion("comp_name between", value1, value2, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotBetween(String value1, String value2) {
            addCriterion("comp_name not between", value1, value2, "compName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_limit
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 27 15:20:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rule_limit
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}