package com.suneee.entity;

import java.util.Date;

public class RuleLimit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.id
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.add_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Integer addNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.add_day
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Integer addDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.surplus_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Integer surplusNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.sdk_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Integer sdkNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.type
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.comp_code
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private String compCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.comp_name
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private String compName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.create_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_limit.update_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.id
     *
     * @return the value of rule_limit.id
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.id
     *
     * @param id the value for rule_limit.id
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.add_num
     *
     * @return the value of rule_limit.add_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Integer getAddNum() {
        return addNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.add_num
     *
     * @param addNum the value for rule_limit.add_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setAddNum(Integer addNum) {
        this.addNum = addNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.add_day
     *
     * @return the value of rule_limit.add_day
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Integer getAddDay() {
        return addDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.add_day
     *
     * @param addDay the value for rule_limit.add_day
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setAddDay(Integer addDay) {
        this.addDay = addDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.surplus_num
     *
     * @return the value of rule_limit.surplus_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Integer getSurplusNum() {
        return surplusNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.surplus_num
     *
     * @param surplusNum the value for rule_limit.surplus_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setSurplusNum(Integer surplusNum) {
        this.surplusNum = surplusNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.sdk_num
     *
     * @return the value of rule_limit.sdk_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Integer getSdkNum() {
        return sdkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.sdk_num
     *
     * @param sdkNum the value for rule_limit.sdk_num
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setSdkNum(Integer sdkNum) {
        this.sdkNum = sdkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.type
     *
     * @return the value of rule_limit.type
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.type
     *
     * @param type the value for rule_limit.type
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.comp_code
     *
     * @return the value of rule_limit.comp_code
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public String getCompCode() {
        return compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.comp_code
     *
     * @param compCode the value for rule_limit.comp_code
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setCompCode(String compCode) {
        this.compCode = compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.comp_name
     *
     * @return the value of rule_limit.comp_name
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.comp_name
     *
     * @param compName the value for rule_limit.comp_name
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setCompName(String compName) {
        this.compName = compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.create_time
     *
     * @return the value of rule_limit.create_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.create_time
     *
     * @param createTime the value for rule_limit.create_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_limit.update_time
     *
     * @return the value of rule_limit.update_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_limit.update_time
     *
     * @param updateTime the value for rule_limit.update_time
     *
     * @mbg.generated Mon Aug 27 15:20:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}