package com.suneee.entity;

import java.util.Date;

public class SecretKeyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.appid
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.appkey
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private String appkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private String compCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.state
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.create_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret_key_info.update_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.id
     *
     * @return the value of secret_key_info.id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.id
     *
     * @param id the value for secret_key_info.id
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.appid
     *
     * @return the value of secret_key_info.appid
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.appid
     *
     * @param appid the value for secret_key_info.appid
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.appkey
     *
     * @return the value of secret_key_info.appkey
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.appkey
     *
     * @param appkey the value for secret_key_info.appkey
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.comp_code
     *
     * @return the value of secret_key_info.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public String getCompCode() {
        return compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.comp_code
     *
     * @param compCode the value for secret_key_info.comp_code
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setCompCode(String compCode) {
        this.compCode = compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.state
     *
     * @return the value of secret_key_info.state
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.state
     *
     * @param state the value for secret_key_info.state
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.create_time
     *
     * @return the value of secret_key_info.create_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.create_time
     *
     * @param createTime the value for secret_key_info.create_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret_key_info.update_time
     *
     * @return the value of secret_key_info.update_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret_key_info.update_time
     *
     * @param updateTime the value for secret_key_info.update_time
     *
     * @mbg.generated Thu Jun 21 17:29:05 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}